### ISSUE TITLE
It could only download Vietnamese subtitle even though I changed to other languages.

### ISSUE THREAD

**Issue by YFTX2015** [AdvMaple/biliintl_subtitle_download_plugin#1]

**Comment by AdvMaple** [comment]
This is my personal script, so I only need Vietnamese subtitles.

If you need to download English or other languages, change line 88 to:

 "en" for English
 "th" for Thai
 "zh-Hans" for Chinese
 "vn" for Vietnamese
 
![image](https://user-images.githubusercontent.com/46006210/132121587-3908fd72-28d4-4dee-889d-d4f9a80580f7.png)

In there future, I might add the option to choose languages.
