### ISSUE TITLE
Show Error

### ISSUE THREAD

**Issue by ivuthemanh** [AdvMaple/biliintl_subtitle_download_plugin#13]
![image](https://user-images.githubusercontent.com/60544875/146871536-d9c118a0-bf4e-4213-8685-6fa0ada122aa.png)
When i run script, it can't show ep number, so I don't know how to find the right episode?
Please help me, thanks!

**Comment by AdvMaple** [comment]
Did you use English for site language? If you got "Tập ??" that mean you are using Vietnamese for main language. Change site language to English and try again.

**Comment by ivuthemanh** [comment]
> Did you use English for site language? If you got "Tập ??" that mean you are using Vietnamese for main language. Change site language to English and try again.

it worked. Thank you!
