### ISSUE TITLE
Downlpad issue

### ISSUE THREAD

**Issue by inuuya** [AdvMaple/biliintl_subtitle_download_plugin#14]
![image](https://user-images.githubusercontent.com/96777876/147570922-d1ed39f5-62db-4abe-b66a-16d14a47eabd.png)

Hi there, I have difficult here! I can't generated the link, and can't possible download the file. please help me!

**Comment by AdvMaple** [comment]
Your screen have to be bigger to have a side menu. The script only work if you have a side menu
![image](https://user-images.githubusercontent.com/46006210/147574566-a349f739-aa89-4f6d-a156-c73dad1e07e4.png)
I'll fix this issue in a future update.

**Comment by inuuya** [comment]
how to make a side menu? Do you set it?


Pada tanggal Sel, 28 Des 2021 pukul 21.09 AdvMaple ***@***.***>
menulis:

**Comment by AdvMaple** [comment]
You can either change your screen size or use your browser dev tool to use responsive view.

**Comment by AdvMaple** [comment]
Reopen because this is a known bug
