### ISSUE TITLE
Script doesn't work

### ISSUE THREAD

**Issue by inuuya** [AdvMaple/biliintl_subtitle_download_plugin#16]
I've tried many times to generated the link but it doesn't work. Idk either, bilibili has updated the new version of their website or we just need the link. Thanks in advance to provide this script to us, it's very helpful!

![image](https://user-images.githubusercontent.com/96777876/149910642-f9bec226-ef1a-4b84-bedb-b776584d6a7d.png)

**Comment by inuuya** [comment]
I mean, we just need the new script :<?

**Comment by AdvMaple** [comment]
![image](https://user-images.githubusercontent.com/46006210/149913733-2896fe2c-eea3-4c8b-92bb-16b81858a18d.png)
I was still able to generate link
Can you check your script version, it should be 0.5.7

**Comment by inuuya** [comment]
sorry, I don't know how to check it, but when I tried to update the script it says that this is the new version
![image](https://user-images.githubusercontent.com/96777876/149916416-9fd598af-7161-4a82-8c8d-902cff3b89c6.png)

**Comment by AdvMaple** [comment]
Click the dashboard and it will show you the version
![image](https://user-images.githubusercontent.com/46006210/149916691-e27e12e3-8c8c-442d-b5bc-7f443b6a904e.png)
One way to make sure you have the latest version is to reinstall the script by click on the install link again:
[link here](https://github.com/AdvMaple/biliintl_subtitle_download_plugin/raw/feature/download.user.js)

**Comment by inuuya** [comment]
I've checked it, and it's the new version 0.5.7. I was tried the other method earlier by deleted Tampermonkey and reinstall it, yet it still same... I can't download the file :( The links aren't showed

**Comment by AdvMaple** [comment]
Have you refresh the page after you reinstall?

**Comment by inuuya** [comment]
I have, I even close the browser and opened it. What should I do?

**Comment by AdvMaple** [comment]
If you can, can you let me control your computer using Team Viewer?

**Comment by inuuya** [comment]
Yeah, sure thing.

**Comment by AdvMaple** [comment]
you can message me through Facebook at: https://www.facebook.com/kmdung2910/
or Twitter at: https://twitter.com/KieuDungg

**Comment by AdvMaple** [comment]
For anyone read this in the future. No problem when I teamview in, the script work fine.

**Comment by ts2812ht** [comment]
> For anyone read this in the future. No problem when I teamview in, the script work fine.

But still, how do I fix this ?

**Comment by AdvMaple** [comment]
@ts2812ht What problem are you having? Can you give me the name of the film/series? What subtitle language are you downloading?

**Comment by ts2812ht** [comment]
I don't know, no matter what series/language, there nothing to download
![image](https://user-images.githubusercontent.com/68367739/175077713-d7a066b3-2066-4bda-9826-afe0313a794c.png)
![image](https://user-images.githubusercontent.com/68367739/175078544-df2605a7-c147-4f2d-bc87-161a317e481a.png)

I tried different browsers, reinstall (ver0.5.9) but same result
Thanks for responding

**Comment by AdvMaple** [comment]
I just tested the plugin, it seem there has been some changes in bilibili site, so the scripts got broken again. I'll try to fix this

**Comment by ts2812ht** [comment]
@AdvMaple So... I should wait for next update ?

**Comment by AdvMaple** [comment]
@ts2812ht Yes, which hopefully not long

**Comment by ts2812ht** [comment]
Thank you for your hard work <3 <3 <3

**Comment by AdvMaple** [comment]
@ts2812ht It should be working now

**Comment by ts2812ht** [comment]
It works perfectly now, thank you
