### ISSUE TITLE
Did they create a search delay?

### ISSUE THREAD

**Issue by Kuju29** [AdvMaple/biliintl_subtitle_download_plugin#20]
After creating a link and pressing refresh more than 4 times, I can't to watch the video. Are you the same as me? Or it just happen only me.

![image](https://user-images.githubusercontent.com/22098092/165033185-47eb179a-93db-4485-a50e-58159b1ad22d.png)

**Comment by AdvMaple** [comment]
I've read the issue but haven't try to reproduce it. I will let you know when I have time to visit the problem.

**Comment by AdvMaple** [comment]
This is not really a search delay. I tried reload page repeatedly, generate link repeatedly and I also can't watch episode after about 10-15 times.  

I think this is bilibili DDOS protection.
![image](https://user-images.githubusercontent.com/46006210/166395257-af513d22-40d1-45fc-9c94-8c645830d215.png)

![image](https://user-images.githubusercontent.com/46006210/166395014-bda0603d-efb5-4065-8de7-072f2b26c494.png)
![image](https://user-images.githubusercontent.com/46006210/166395319-0ad87b7f-522a-4fc0-a10b-6336ec9c1156.png)

**Comment by Kuju29** [comment]
> This is not really a search delay. I tried reload page repeatedly, generate link repeatedly and I also can't watch episode after about 10-15 times.
> 
> I think this is bilibili DDOS protection. ![image](https://user-images.githubusercontent.com/46006210/166395257-af513d22-40d1-45fc-9c94-8c645830d215.png)
> 
> ![image](https://user-images.githubusercontent.com/46006210/166395014-bda0603d-efb5-4065-8de7-072f2b26c494.png) ![image](https://user-images.githubusercontent.com/46006210/166395319-0ad87b7f-522a-4fc0-a10b-6336ec9c1156.png)

Thanks for reply
You may need to add a delay for each link generation. Like the netflix plugin, they create a delay in opening the next episode so that it doesn't get blocked. Or maybe you have a better way. <3

[netflix plugin](https://greasyfork.org/scripts/26654-netflix-subtitle-downloader)

**Comment by AdvMaple** [comment]
@Kuju29 I think I will have to disable "All Episode" option. This will reduce the number of API calls.

**Comment by AdvMaple** [comment]
close with [5af0a64](https://github.com/AdvMaple/biliint.com-bilibili.tv_subtitle_download_plugin/commit/5af0a64aa4e00ee26e42e45278673c394b75a225)
