### ISSUE TITLE
Can you put a quick little "How To Use" not just a "How to Install"?

### ISSUE THREAD

**Issue by LostOnTheLine** [AdvMaple/biliintl_subtitle_download_plugin#25]
i'm attempting to get the subtitles for this video
https://www.bilibili.tv/en/video/2048172682

I installed Tampermonkey, clicked the link, Installed the script. Tampermonkey lists it under the `Installed Userscripts` & it is marked as `Enabled`

What do I do from there?

On the video I never see the popup in the lower left corner for Subtitles to download. Looking at the .gif there appears to be some sort of right-click somewhere that I cannot figure out

**Comment by AdvMaple** [comment]
Sorry, my script only support series, not single video

**Comment by LostOnTheLine** [comment]
Ah. that makes sense why it wasn't working. Disappointing, but understandable. Do you know if there are any other options that do support single videos? Subtitles particularly as that's what I'm mostly looking for
