### ISSUE TITLE
Server is returning wrong 

### ISSUE THREAD

**Issue by cjrayance** [AdvMaple/biliintl_subtitle_download_plugin#29]
https://user-images.githubusercontent.com/122617363/228818593-85475dfc-c235-40b4-b725-6280968d3f38.mp4

**Comment by cjrayance** [comment]
I've tried disabling AdGuard and the subtitles appear to download.


https://user-images.githubusercontent.com/122617363/228819935-adf8c191-0a80-4fe8-964e-82523e874b47.mp4

**Comment by AdvMaple** [comment]
Nice work! Thank you for notice that
