### ISSUE TITLE
empty subtitle

### ISSUE THREAD

**Issue by tuanden0** [AdvMaple/biliintl_subtitle_download_plugin#33]
New version can download ass file on bilibili, but if there is no ass file, instead of download srt for fallback such as previous, it generate and download empty ass file.

Could you update this behavior?

Thank you.

**Comment by calavikevin** [comment]
ok, i will update soon

**Comment by calavikevin** [comment]
I resolved this issue in pull request #34

**Comment by tuanden0** [comment]
@NhatPhuong, the problem still be there with version 0.7.2,

for example: with this url `https://www.bilibili.tv/vi/play/2084136/12841457?bstar_from=bstar-web.pgc-video-detail.episode.all` I chose "Vietnamese" and "ass" for episode 0. It still generate and download empty ass file.

Could you please re-check this problem?

Edited:
I had checked the downloaded ass file, turn out the downloaded content was invalid, it stored all json subtitle format into ass file format.

Here is wrong content example in ass file:
```{"font_size":0.4,"font_color":"#FFFFFF","background_alpha":0.5,"background_color":"#9C27B0","Stroke":"none","body":[{"from":66.08,"to":68.59,"location":2,"content":"Thế đó là màu gì vậy?"},{"from":68.94,"to":70.57,"location":2,"content":"Một màu hồng tuyệt mỹ."},{"from":70.57,"to":73.77,"location":2,"content":"À không, có pha một chút màu cam ạ."},{"from":77.58,"to":79.14,"location":2,"content":"Quả nhiên là ta..."}```

**Comment by calavikevin** [comment]
This is a common problem with bilibili. Actually, not all episodes on bilibili have subtitles in .ass format available. With the Vietnamese language, the popular format that bilibili supports is still srt (stored in json format), and only a few recent movies support the .ass format in parallel with .srt.

**Comment by NhatPhuong** [comment]
![Uploading IMG_0005.jpeg…]()

**Comment by calavikevin** [comment]
![image](https://github.com/AdvMaple/bilibili-subtitle-download-plugin/assets/6884546/f773947b-5005-4ce2-90bf-b8de7900f855)

For example, in the episode you shared above, .ass is only available in English. But Vietnamese only has json (srt). In this case the plugin will automatically convert the json content into .ass format because the .ass file is not available

**Comment by tuanden0** [comment]
@NhatPhuong thank for the explanation, I understood that not every episode has the ass file.

But on version `0.5.12` if the ass format not exists, it automatically download srt format, not json format content in ass format and it is the correct way. Because the ass format has it own metadata to read.

I think there is something wrong with `the plugin will automatically convert the json content into .ass format`

Updated:
I think it could be great if ass file does not exists, it will download the srt file instead of convert json content to ass file.

For example:
This is correct ass format for the ass subtitle style:
```[Script Info]
Title: Bilibili Subtitle
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.601
PlayResX: 1920
PlayResY: 1080

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Noto Sans,100,&H00FFFFFF,&H000000FF,&H00002208,&H80000000,-1,0,0,0,100,100,0,0,1,5,1.5,2,0,0,65,1
Style: Banner,Noto Sans,80,&H00D89815,&H000000FF,&H00FFFFFF,&H00000000,-1,0,0,0,100,100,0,0,1,5,1.5,8,10,10,10,1
Style: Default Above,Noto Sans,100,&H00FFFFFF,&H000000FF,&H00002208,&H80000000,-1,0,0,0,100,100,0,0,1,5,1.5,8,0,0,65,1
Style: 5-normal,Noto Sans,65,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,0,5,10,10,10,1
Style: 6-normal,Noto Sans,65,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,0,6,10,10,10,1
Style: 4-normal,Noto Sans,65,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,0,4,10,10,10,1
Style: Screen - 复制,Noto Sans,65,&H007E5A54,&H00FFFFFF,&H00000000,&H7F000000,0,0,0,0,100,100,0,0,1,0,0,2,96,96,0,1
Style: Screen,Noto Sans,65,&H00FFFFFF,&H00FFFFFF,&H00000000,&H7F000000,-1,0,0,0,100,100,0,0,1,2,1.5,2,96,96,0,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:01:07.75,0:01:11.80,5-normal,,0,0,0,,{\1c&H000000&\3c&HFFFFFF&\bord4\fad(700,200)\pos(1282,240)}Công Tước Tử Thần Và Cô Hầu 2
Dialogue: 0,0:02:27.00,0:02:31.08,5-normal,,0,0,0,,{\1c&H000000&\3c&HFFFFFF&\bord4\blur4\fs55\fad(0,300)\pos(476,824)}Tập 20 \N Cậu chủ và Alice và nụ hôn trên cửa sổ
Dialogue: 0,0:02:38.64,0:02:43.60,5-normal,,0,0,0,,{\1c&H536288&\3c&H7797A6&\bord6\move(1256,86,1202,88,18,1145)}Rạp xiếc\NGemini
Dialogue: 0,0:02:38.64,0:02:43.60,5-normal,,0,0,0,,{\1c&H536288&\3c&H536288&\move(1256,86,1202,88,18,1145)}Rạp xiếc\NGemini
Dialogue: 0,0:11:22.99,0:11:28.00,5-normal,,0,0,0,,{\fad(900,0)\pos(982,442)}Công Tước Tử Thần Và Cô Hầu 2
Dialogue: 0,0:23:35.01,0:23:40.76,5-normal,,0,0,0,,{\1c&H000000&\bord1\pos(926.666,50)}Công Tước Tử Thần Và Cô Hầu 2```

**Comment by calavikevin** [comment]
Automatic conversion from json to ass has been added by me since version 0.7 as part of the feature. Instead, there will be a message indicating the file format that will be returned by the server and the file format that will be downloaded.

**Comment by calavikevin** [comment]
I will consider your comments and may update in the next version. Thank you for your comments.

**Comment by AdvMaple** [comment]
> Automatic conversion from json to ass has been added by me since version 0.7 as part of the feature. Instead, there will be a message indicating the file format that will be returned by the server and the file format that will be downloaded.

Yeah, I think you should add an alert to the user if the file downloaded is not what user currently chose.
There is a logic in `processSubtitleArrayFromServer` and a simple function `_isAssSubtitleFile` for this cases.
You can read the current file to see if the file downloaded is .ass file or not.

There is also some function to convert json subtitle to other format as well for you to use

**Comment by calavikevin** [comment]
Based on @tuanden0 and @AdvMaple 's suggestions, there have been some changes updated in pull request #37
