### ISSUE TITLE
I followed the guide but to no avail. Is this project still updated? 

### ISSUE THREAD

**Issue by laovvai** [AdvMaple/biliintl_subtitle_download_plugin#38]
Hey! 
Sorry to open a new issue but I installed this plugin and nothing happened. 
Tampermonkey just doesn't run this script when I'm browsing on bilibili. 
It would be incredible if I could download at least subtitles, it would help me a great deal with my Chinese studies. 
Thanks in advance!

**Comment by calavikevin** [comment]
I quickly checked, the plugin still works well and no unexpected errors appeared.

Please provide the video link, I will check for you. Make sure the video is from bilibili.tv and supports subtitles (not hardsub into the video) in the language you choose.

![image](https://github.com/AdvMaple/bilibili-subtitle-download-plugin/assets/6884546/63e1d036-92f7-48ea-8868-d33b846f0cc2)

**Comment by AdvMaple** [comment]
Close due to inactivity, feel free to re-open
