### ISSUE TITLE
Support `/video` endpoint

### ISSUE THREAD

**Issue by datlmhg** [AdvMaple/biliintl_subtitle_download_plugin#39]
It doesn't seem to be able to get the subtitle from long-term videos :((

![image](https://github.com/AdvMaple/bilibili-subtitle-download-plugin/assets/86174857/f3b67da5-7938-4da2-8508-b17567ed9316)

**Comment by AdvMaple** [comment]
Can you provide the video link?

**Comment by datlmhg** [comment]
> Can you provide the video link?

here: https://www.bilibili.tv/en/video/4786384793243136

**Comment by AdvMaple** [comment]
[GOT7 - Fancon 'Homecoming with I GOT 7' [2022.05.21].zip](https://github.com/AdvMaple/bilibili-subtitle-download-plugin/files/13749241/GOT7.-.Fancon.Homecoming.with.I.GOT.7.2022.05.21.zip)
Here is the subtitle, the code right now not supporting the video you sent. Will fix that when I have free time to test.

**Comment by datlmhg** [comment]
> [GOT7 - Fancon 'Homecoming with I GOT 7' [2022.05.21].zip](https://github.com/AdvMaple/bilibili-subtitle-download-plugin/files/13749241/GOT7.-.Fancon.Homecoming.with.I.GOT.7.2022.05.21.zip) Here is the subtitle, the code right now not supporting the video you sent. Will fix that when I have free time to test.

thank u so much

**Comment by calavikevin** [comment]
I will have an update soon.

**Comment by calavikevin** [comment]
Solved this issue in Pull request #40

**Comment by datlmhg** [comment]
> Solved this issue in Pull request #40

I see it's been updated to version 0.7.4, but the script link is still 0.7.3, right?

**Comment by calavikevin** [comment]
> > Solved this issue in Pull request #40
> 
> I see it's been updated to version 0.7.4, but the script link is still 0.7.3, right?

0.7.4 is the next version that I am asking to update. Please wait for the author to accept my pull request before you can use this version

**Comment by calavikevin** [comment]
@AdvMaple This issue has been resolved, pls close it.
