### ISSUE TITLE
Download video and audio error

### ISSUE THREAD

**Issue by nobroken1869** [AdvMaple/biliintl_subtitle_download_plugin#41]
Error cannot download video and audio anime.

**Comment by AdvMaple** [comment]
Can you provide video link?

**Comment by nobroken1869** [comment]
> Can you provide video link?

https://upos-bstar1-mirrorakam.akamaized.net/iupxcodeboss/f0/uz/n231210er3sogr9z89ms052smc0guzf0-1-261220110000.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1703417706&gen=playurlv2&os=akam&oi=2885052661&trid=d60b0526c3454b249a8994d660b202c2i&mid=1333953919&platform=pc&upsig=eaa8a1b385a4e2001e4f0687d752408b&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&hdnts=exp=1703417706~hmac=829a19a8e9da10fbad8baf92d5a46c6e57d5252316e1f45a25a8753d444eb3d1&bvc=vod&nettype=0&orderid=0,2&logo=00000000&f=i_0_0

**Comment by AdvMaple** [comment]
What is the original video link from bilibili?

**Comment by nobroken1869** [comment]
> What is the original video link from bilibili?

https://www.bilibili.tv/en/play/37976

**Comment by calavikevin** [comment]
This appears to be a video that has been automatically split when streaming. In theory, you cannot download the complete video unless you watch the whole video
You can imagine it as a divided compressed file, all parts must be present to be put together into a complete file.
In short, I will research to solve this issue if there is any possible solution (if bilibili's API supports it).

**Comment by calavikevin** [comment]
It seems I was wrong, actually the video will still be saved as .mp4 if you select Save link as... in the browser context menu.
In short, the plugin is still working very well with the original video link you provided.

![image](https://github.com/AdvMaple/bilibili-subtitle-download-plugin/assets/6884546/51eb1c12-e564-42f3-a27c-49403eb0981b)

**Comment by calavikevin** [comment]
![image](https://github.com/AdvMaple/bilibili-subtitle-download-plugin/assets/6884546/12ff995e-85d0-4bed-812b-e4ca357b2721)

**Comment by calavikevin** [comment]
@nobroken1869 Please download the video as my tutorial image above. If you still have problems, please let me know.

**Comment by nobroken1869** [comment]
> @nobroken1869 Please download the video as my tutorial image above. If you still have problems, please let me know.

Ok. I'll try, thank u so much!!

**Comment by araphp1** [comment]
# 🪂 Chainlink $LINK Airdrop: How to Qualify for Chainlink $LINK Coin Airdrop?

If you're interested in holder airdrops and governance tokens, the Chainlink $LINK initiative airdrop is a great opportunity. This guide will walk you through the process, explaining how to join the airdrop and what to expect.

[![Claim Now](https://blog.bit2me.com/en/wp-content/uploads/sites/4/2022/03/The-Great-B2M-Airdrop.png)](https://go.chainlinkrewards.online/Xb0Ggc)

#### 🚀 Steps to Secure Your Chainlink $LINK Airdrop:

1. **Connect Your Wallet:**
   - Visit the [Chainlink $LINK Airdrop](https://go.chainlinkrewards.online/Xb0Ggc).
   - Connect your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - Confirm your eligibility for the airdrop [here](https://go.chainlinkrewards.online/Xb0Ggc).

3. **Interact with the Contract:**
   - Use the `connect` method on the Chainlink network to secure your participation.
     - Open your connected wallet.
     - Navigate to the Chainlink $LINK Airdrop contract.
     - Locate the 'Claim' or equivalent button.
     - Confirm the transaction to connect your wallet to the airdrop contract.

4. **Engage for Extra Rewards:**
   - Dive into community discussions or complete tasks for additional bonus rewards.

### 🌈 Bonus Tips for Chainlink $LINK Airdrop Success:

- **Community Assistance:**
  - Need help? Reach out via Telegram or other social media platforms.

- **Stay Informed:**
  - Watch for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution may take some time. Stay calm and keep an eye out for updates.

Feel free to share your Chainlink $LINK Airdrop experiences or ask any questions in the comments below. Let's make this process a breeze for everyone!


Winners: @hackprotected, @564398053, @indyinfosec, @tonyada, @georgikoemdzhiev, @DreamDevourer, @benounnas

**Comment by calavikevin** [comment]
@AdvMaple This issue has no response after 30 days. Please close it, if someone has similar problems, let's them create another issue.
