### ISSUE TITLE
Can't identify video ID.

### ISSUE THREAD

**Issue by neolin0629** [AdvMaple/biliintl_subtitle_download_plugin#43]
When I open any video page, an error message pops up as shown in the following picture. I don't know what could be the reason?

For example: https://www.bilibili.com/video/BV1xt4y1f7om

![image](https://github.com/AdvMaple/bilibili-subtitle-download-plugin/assets/26494876/5ebd5549-a2b8-4160-8c54-e8aecf9f3ded)

**Comment by calavikevin** [comment]
This plugin currently only supports bilibili.tv as I haven't had time to test compatibility with bilibili.com.

It seems like this is a bug because bilibili.com has a different url format with bilibili.tv

**Comment by neolin0629** [comment]
Thanks for your reply.
