### ISSUE TITLE
Not downloading

### ISSUE THREAD

**Issue by jjaruna** [AdvMaple/biliintl_subtitle_download_plugin#45]
Hi, I am trying to download this video: https://www.bilibili.tv/en/video/4787455373613568?bstar_from=bstar-web.my-history-all.0.0

and it stays as shown in the picture. Is there any way to download it or am I doing something wrong? 

![bd03eb93-00c0-44dd-bea1-e7bb5216e0ac](https://github.com/AdvMaple/bilibili-subtitle-download-plugin/assets/106907367/f594c7c9-855a-4aca-83c1-0c81f9092e24)

**Comment by calavikevin** [comment]
Right-click on the path, then select "Save as..."

**Comment by jjaruna** [comment]
> Right-click on the path, then select "Save as..."

It doesn't let me either, if you do it, will it let you ?
![2000349429270_2](https://github.com/AdvMaple/bilibili-subtitle-download-plugin/assets/106907367/67f6f90c-27a0-4739-ace8-55a5254fc56e)

**Comment by calavikevin** [comment]
Right click on the path from download link of plugin

**Comment by calavikevin** [comment]
![image](https://github.com/AdvMaple/bilibili-subtitle-download-plugin/assets/6884546/ca6734c3-8f74-4eac-a6da-7245dd6fe49a)

**Comment by jjaruna** [comment]
> Right click on the path from download link of plugin

OMG I'm an idiot lmao, thank you very much for the help. It will help me to download a lot of videos!

**Comment by jjaruna** [comment]
Hi, sorry to reopen the thread. I'm programming a video downloader from BiliBili.tv where I automatically join the video and audio using FFmpeg. 

I'm using CLI and Python, but I have a problem, since it's my first time querying the BiliBili API. When I try to download videos longer than 10 minutes, it limits the file download and only processes 12.5MB, making the file corrupt.
![46567756756](https://github.com/AdvMaple/bilibili-subtitle-download-plugin/assets/106907367/801393aa-86a9-46ed-a535-3d4441590db0)

This is the request I make to get the url of the video in 720 quality.

![def1](https://github.com/AdvMaple/bilibili-subtitle-download-plugin/assets/106907367/96e97033-f984-4e0e-aab4-36b4be6b14db)


I'm seeing that in your program, you make the API request and include a: { credentials: "include" }

Any idea?

I apologize for asking here, but I don't have where and I didn't find API docs to see how to do it.

**Comment by AdvMaple** [comment]
For the 
> When I try to download videos longer than 10 minutes, it limits the file download and only processes 12.5MB, making the file corrupt.  

I really don't know why, this can be caused by many reasons: file type, the code you implement, the server limit, load balance, so can't help you here.  

But for the 

> I'm seeing that in your program, you make the API request and include a: { credentials: "include" }  

This is because Bilibili authenticate your request using cookie, and not by header.

**Comment by jjaruna** [comment]
Thank you for your help, I am now including the Cookies option.

You will not believe me, but I just downloaded the video that has not let me all day and just let me lmao.

The BiliBili API works very weird lol

**Comment by jjaruna** [comment]
I update

I tried adding the cookies to the request and it didn't work either. In fact since the comment I posted above, saying it let me download, now it won't let me download the video files at 100%, they corrupt at 12%.

I don't know what to do anymore  xD

**Comment by AdvMaple** [comment]
Afraid beyond helping you with the API and the authentication as I said above, I can't help you further because of limited knowledge of your code.
